version: '3'
services:
  web_service:
    build: ./web_service
    ports:
      - "5000:5000"
    volumes:
      - ./web_service/config:/app/config
    networks:
      - ajay_network  

  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_service
    networks:
      - ajay_network  